const router = require('express').Router();
const controller = require('./tenant.controller');
const authenticate = require('../../middlewares/auth.middleware');
const authorizeRoles = require('../../middlewares/role.middleware');
router.use(authenticate);
router.get('/', authorizeRoles('manager', 'staff'), controller.list);
router.get('/:id', authorizeRoles('manager', 'staff'), controller.getById);
router.post('/', authorizeRoles('manager'), controller.create);
router.put('/:id', authorizeRoles('manager'), controller.update);
router.delete('/:id', authorizeRoles('manager'), controller.remove);
module.exports = router;
